language: node_js
node_js:
    - "stable"

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

services:
  - postgres

before_script:
    - psql -c 'create database dms_test;' -U postgres
    - npm run migrate:test
    - npm install

script:
  - npm test

after_success:
  - cat coverage/*lcov.info | ./node_modules/.bin/coveralls 

addons:
  postgresql: "9.3"